### PR TITLE
Filter items and disable items

### PR DESCRIPTION
**Pull request by Amerlander**
I added two options: `filter` and `disable`.

You can define functions to disable elements (they are shown, but not selectable any more) or to filter them out (they are not showing up at all).

I use this to either disable selected item or to hide them on the fly.

E.g.
```
<script>
    const extract = (item) => item.titel;
    const disable = (item) => item.title.length > 4;
    const filter = (item) => item.title.length > 8;
</script>

<Typeahead {data} {extract} {disable} {filter}>
```

```
<script>
   function handleSelect(e) {  
        let i = e.detail.originalIndex;
        data[i].selected = true;
    }
    
    const extract = (item) => item.titel;
    const disable = (item) => item.selected;
</script>

<Typeahead {data} {extract} {disable} on:select="{handleSelect}">
```

### CODE REVIEW

**Comment by metonym** [comment]
Very cool. Could you add those usage examples to the README for documentation?

**Review by metonym — CHANGES_REQUESTED** [review]
Needs documentation:

- document props/usage in README.md
- update TypeScript definitions in `types/Typeahead.d.ts`

**Review by metonym — APPROVED** [review]

**Comment by Amerlander** [comment]
Thank you for accepting and merging my changes! :)

**Comment by metonym** [comment]
Thanks for contributing – the `disable/filter` behavior is elegantly designed

**Comment by metonym** [comment]
Published in v2.3.0 to NPM.

**Pull request merged**
