### PR TITLE
Export SearchRef for focusing

### PR DESCRIPTION
**Pull request by Amerlander**
I formerly said I could call `this.focus()` from outside. That was wrong and I do not know in what state my code was then that it had worked.

So this pr adds up on https://github.com/metonym/svelte-typeahead/issues/11. To keep the behavior as it is it would be great for me to be able to focus from outside.

Also the `select` event had to be dispatched after the dropdown is closed, therefore I moved it to the end of the function.

If you dont mind I would be happy to see this code merged, otherwise I`ll just keep it for myself. :)

The only downside is, that I have to set `focusAfterSelect` to `false` to be able to actually focus after select. If I keep it to true the focus event wouldn't trigger the focus event.

### CODE REVIEW

**Comment by metonym** [comment]
what do you want to accomplish here? give me an example and lay put the expected behavior

**Comment by Amerlander** [comment]
I want to be able to select multiple items without having to refocus the input field between each selection.

I've made two Videos here: https://github.com/metonym/svelte-typeahead/issues/11#issuecomment-782876317
The first is the actual behavior, the second one is what I want.

**Comment by metonym** [comment]
I appreciate the PR but I'm not interested in having this module emulate a multi-select filter behavior.

**Comment by Amerlander** [comment]
Without dispatching the select event after setting `hideDropdown` to `true` it would not help me to have the searchRef exposed, since it will overwrite my attemptions to reopen it in the select event.

It think I just g owith my forked repo and change the behaviour of `focusAfterSelect` to fit my expectations:

```
if (focusAfterSelect) {
  searchRef.focus();
} else {
  hideDropdown = true;
}
```

**Comment by Amerlander** [comment]
I renamed my forked repo `svelte-typeahead-multiselect`, since I mostly need it as a multiselect and think it might be more clear to others. I'll still try to keep everything else in sync with your repo. I hope you are okay with that.

**Pull request closed without merging**
